import { ProductClassification, IPRoadmap } from "./types";

export const mockClassification: ProductClassification = {
  formulation_type: "proprietary",
  biological_resources: true,
  indian_bio_resources: true,
  tk_involved: true,
  target_markets: ["India", "Germany"],
  domains: ["patent", "trademark", "abs", "regulatory"],
  clarifying_questions: [
    "Is the extraction method for Ashwagandha significantly different from classical texts?",
    "Do you have evidence of enhanced efficacy (synergism) for the combination of Ashwagandha and Shallaki?",
  ],
  confidence: 0.82,
};

export const mockRoadmap: IPRoadmap = {
  product_assessment: {
    summary:
      "A proprietary non-classical Ayurvedic formulation combining Ashwagandha and Shallaki for joint pain, intended for markets in India and Germany.",
    formulation_type: "proprietary",
  },
  domains: [
    {
      domain: "patent",
      status: "insufficient_evidence",
      finding:
        "Under Section 3(p) of the Patents Act 1970, traditional knowledge is not patentable. To secure a patent, you must prove that the combination exhibits synergistic effects rather than a mere admixture.",
      confidence: 0.65,
      citations: [
        {
          chunk_id: "sec_3p_1970",
          doc_title: "The Patents Act, 1970",
          section: "Section 3(p)",
          source_url: "https://ipindia.gov.in/writereaddata/Portal/ev/sections/ps3.html",
          retrieved_at: "2026-08-22T00:00:00Z",
        },
      ],
      escalation_required: true,
    },
    {
      domain: "abs",
      status: "ok",
      finding:
        "Since the formulation relies on Indian biological resources (Ashwagandha and Shallaki), compliance with the Biological Diversity Act, 2002 is required. You must seek approval from the National Biodiversity Authority (NBA) prior to obtaining IP rights or commercializing internationally.",
      confidence: 0.95,
      citations: [
        {
          chunk_id: "bda_2002_sec3",
          doc_title: "Biological Diversity Act, 2002",
          section: "Section 3 & 6",
          source_url: "http://nbaindia.org/content/25/19/1/act.html",
          retrieved_at: "2026-08-22T00:00:00Z",
        },
      ],
      escalation_required: false,
    },
    {
      domain: "regulatory",
      status: "ok",
      finding:
        "For marketing in Germany, the product may be subject to the Traditional Herbal Medicinal Products Directive (THMPD) under EU regulations or require classification as a food supplement, depending on the claims made.",
      confidence: 0.88,
      citations: [
        {
          chunk_id: "eu_thmpd_2004",
          doc_title: "EU Directive 2004/24/EC",
          section: "Article 16a",
          source_url: "https://eur-lex.europa.eu/",
          retrieved_at: "2026-08-22T00:00:00Z",
        },
      ],
      escalation_required: true,
    },
    {
      domain: "trademark",
      status: "ok",
      finding:
        "A strong, distinct brand name should be selected and registered in both India (Trade Marks Registry) and the EU (EUIPO). Ensure the name does not simply describe the ingredients.",
      confidence: 0.92,
      citations: [],
      escalation_required: false,
    },
  ],
  jurisdiction_notes: [
    {
      jurisdiction: "India",
      note: "Strict limitations on patenting traditional knowledge. Mandatory NBA approval for biological resources.",
    },
    {
      jurisdiction: "Germany (EU)",
      note: "Stringent regulatory framework for herbal medicines vs. food supplements. IP rights require regional filings (EPO/EUIPO).",
    },
  ],
  next_steps: [
    "Compile clinical or laboratory evidence demonstrating synergistic effects of the formulation.",
    "File Form I with the National Biodiversity Authority (NBA) for access to biological resources.",
    "Consult a European regulatory expert regarding the classification (Herbal Medicine vs. Food Supplement) in Germany.",
  ],
  human_escalation: [
    {
      reason: "Need to establish patentability over traditional knowledge (Section 3(p)) by proving synergism.",
      professional_category: "Patent Attorney",
      severity: "high",
    },
    {
      reason: "Clarify regulatory pathway and compliance requirements for the German market.",
      professional_category: "EU Regulatory Consultant",
      severity: "medium",
    },
  ],
  overall_confidence: 0.85,
  disclaimer:
    "This roadmap is generated by AI and is intended for informational purposes only. It does not constitute legal advice. Please consult with qualified IP attorneys and regulatory professionals.",
};
